### ISSUE TITLE
Apollo data not being server rendered

### ISSUE THREAD

**Issue by nyl-auster** [alidcastano/rogue.js#34] opened 2018-07-07 07:31 UTC
Hello !
Here is what i tried for now, but this is not server side rendered : 

https://github.com/nyl-auster/roguepress/blob/7956588023c0524533e172f54e1159284be4fb50/src/themes/default/components/pages/PostListPage.js

And here is my App.js
https://github.com/nyl-auster/roguepress/blob/7956588023c0524533e172f54e1159284be4fb50/src/App.js

Any suggestions ? Will be glad to complete README about this point :)

**Comment by alidcastano** [comment] 2018-07-08 03:31
Yea, I just confirmed this isn't working

the issue is that we're not wrapping the app passed to `getDataFromTree` in a router or apollo provider 

I'll have fix coming soon

**Comment by alidcastano** [comment] 2018-07-08 21:39
this is fixed in next release; I verified it with your repo

I'll publish package/new documentation hopefully by tonight

**Closed by alidcastano** 2018-07-08 21:39 UTC
Labels: bug
